disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "l0w3"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "nono"
secondaryLogo = "logo.jpeg"

  [params.author]
  name = "l0w3"
  email = "info@l0w3.com"
  image = "logo.jpeg"
  headline = "Offensive security blog"
  bio = "Malware, Vulnerability Research, Hardware Hacking & more"

    [[params.author.links]]
    email = "mailto:info@l0w3.com"
